name: PublishToCocoa

on:
  release:
    types: published
    branches: master
  workflow_dispatch:

jobs:                 
  publish-release:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install CocoaPods
        run: pod install
      - name: Verify and Push
        run: pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
